name: Publish

on:
  release:
    types: [created, published]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.3.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: NPM
        run: npm install
      - name: Publish
        run: npm run release
        env:
          VER: ${{ github.ref }}
          WEXT_SHIPIT_CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
          WEXT_SHIPIT_CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          WEXT_SHIPIT_CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          WEXT_SHIPIT_CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
          WEXT_SHIPIT_FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
          WEXT_SHIPIT_FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
